[package]
name = "rfetch"
version = "0.1.0"
authors = ["alepheia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "1.0.3"
semver = "0.11.0"
sys-info = "0.7.0"
colored = "2.0.0"
